# 首页配置
home:
  hero:
    name: 晳粊的人生 # 名称
    intro: zhì bǐ (与“陟彼”发音相同) # 个人简介
    avatar: /images/avatar.webp # 头像
  posts: recent # recent: 最新文章 | recommend: 推荐文章

# 所有文章
articles:
  path: 'posts' # 路由
  per_page: 10 # 分页数
  order_by: -date # 文章排序

# 菜单栏
menu:
  - name: 主页
    url: /
  - name: 归档
    url: /archives/
  - name: 番剧
    url: /anime/
  - name: 足迹
    url: /footprints/
  - name: 友链
    url: /friends/
  - name: 关于
    url: /about/
  - name: 开往
    url: https://www.travellings.cn/go.html

comment:
  enable: true
  type: twikoo

# Twikoo https://twikoo.js.org/
twikoo:
  envId: https://twikoo.395718.xyz/.netlify/functions/twikoo
  lang: zh-CN

search:
  enable: true
  type: pagefind

# 友链模块
friends:
  - name: Astro
    avatar: https://avatars.githubusercontent.com/u/44914786?v=4&s=640
    link: https://github.com/withastro/astro
    desc: The web framework for content-driven websites
  - name: Mizuki Docs
    avatar: http://q.qlogo.cn/headimg_dl?dst_uin=3231515355&spec=640&img_type=jpg
    link: https://docs.mizuki.mysqil.com
    desc: Mizuki User Manual
  - name: 晳粊
    avatar: https://www.zhbi.top/_astro/avatar.CyWaYkSr_qqU2U.webp
    link: https://zhbi.top
    desc: 人生如登高，山川日月在目，而晳粊之光，独照我心

footer:
  builtUpTime: 2025-11-01 00:00:00

# 社交链接
socialLink:
  - name: Bilibili
    link: https://space.bilibili.com/701864046
  - name: RSS
    link: /atom.xml

# 主题色
primaryColor: '#10b981'

favicon: /favicon.ico # Favicon 图标
